### ISSUE TITLE
DRS

### ISSUE THREAD

**Issue by Reyesjessica** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-ija#1]
https://github.com/SistemasTecTlaxiaco/ProyectosComunitarios/wiki

**Comment by RicardoMtzSts** [comment]
28/30 Bien cumple con los criterios de la rúbrica, aunque se podría poner énfasis a unos puntos: Son claros, pero algunos objetivos específicos podrían desarrollarse más para vincularse mejor con los requisitos. Mejorar en explicación de propósito; precondiciones y excepciones: bien definidas, aunque pueden beneficiarse de más detalles en casos excepcionales complejos.
>>Optimizar el flujo de tareas repetitivas.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
